#############################################################################
# Makefile for building: GPSDeniedNavigation
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  GPSDeniedNavigation.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GPSDeniedNavigation.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include/opencv2 -Imavlink/include/c_library_v2/common -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GPSDeniedNavigation1.0.0
DISTDIR = /home/dev/GPSDeniedNavigation/.tmp/GPSDeniedNavigation1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/usr/local/lib/aarch64-linux-gnu -lopencv_core -lopencv_dnn -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -lopencv_videoio -lopencv_cudaimgproc -lopencv_cudawarping -lopencv_cudaarithm -lopencv_cudafilters -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		serial.cpp \
		camera.cpp \
		telemetry.cpp 
OBJECTS       = main.o \
		serial.o \
		camera.o \
		telemetry.o
DIST          = /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GPSDeniedNavigation.pro serial.h \
		camera.h \
		telemetry.h main.cpp \
		serial.cpp \
		camera.cpp \
		telemetry.cpp
QMAKE_TARGET  = GPSDeniedNavigation
DESTDIR       = 
TARGET        = GPSDeniedNavigation


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPSDeniedNavigation.pro /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GPSDeniedNavigation.pro \
		/usr/lib/aarch64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile GPSDeniedNavigation.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
GPSDeniedNavigation.pro:
/usr/lib/aarch64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GPSDeniedNavigation.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents serial.h camera.h telemetry.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp serial.cpp camera.cpp telemetry.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp serial.h \
		telemetry.h \
		mavlink/include/c_library_v2/common/mavlink.h \
		mavlink/include/c_library_v2/common/version.h \
		mavlink/include/c_library_v2/common/common.h \
		mavlink/include/c_library_v2/protocol.h \
		mavlink/include/c_library_v2/mavlink_types.h \
		mavlink/include/c_library_v2/mavlink_helpers.h \
		mavlink/include/c_library_v2/checksum.h \
		mavlink/include/c_library_v2/mavlink_conversions.h \
		mavlink/include/c_library_v2/mavlink_sha256.h \
		mavlink/include/c_library_v2/common/mavlink_msg_heartbeat.h \
		mavlink/include/c_library_v2/common/mavlink_msg_sys_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_system_time.h \
		mavlink/include/c_library_v2/common/mavlink_msg_ping.h \
		mavlink/include/c_library_v2/common/mavlink_msg_change_operator_control.h \
		mavlink/include/c_library_v2/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_auth_key.h \
		mavlink/include/c_library_v2/common/mavlink_msg_link_node_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_mode.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_request_read.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_value.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_set.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_raw_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_imu.h \
		mavlink/include/c_library_v2/common/mavlink_msg_raw_imu.h \
		mavlink/include/c_library_v2/common/mavlink_msg_raw_pressure.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_pressure.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude_quaternion.h \
		mavlink/include/c_library_v2/common/mavlink_msg_local_position_ned.h \
		mavlink/include/c_library_v2/common/mavlink_msg_global_position_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_servo_output_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_item.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_set_current.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_current.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_count.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_clear_all.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_item_reached.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_global_origin.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_map_rc.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_changed.h \
		mavlink/include/c_library_v2/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/include/c_library_v2/common/mavlink_msg_safety_allowed_area.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_nav_controller_output.h \
		mavlink/include/c_library_v2/common/mavlink_msg_global_position_int_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels.h \
		mavlink/include/c_library_v2/common/mavlink_msg_request_data_stream.h \
		mavlink/include/c_library_v2/common/mavlink_msg_data_stream.h \
		mavlink/include/c_library_v2/common/mavlink_msg_manual_control.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels_override.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_item_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vfr_hud.h \
		mavlink/include/c_library_v2/common/mavlink_msg_command_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_command_long.h \
		mavlink/include/c_library_v2/common/mavlink_msg_command_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_manual_setpoint.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_attitude_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/include/c_library_v2/common/mavlink_msg_position_target_local_ned.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_position_target_global_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_controls.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_actuator_controls.h \
		mavlink/include/c_library_v2/common/mavlink_msg_optical_flow.h \
		mavlink/include/c_library_v2/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vision_position_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_highres_imu.h \
		mavlink/include/c_library_v2/common/mavlink_msg_optical_flow_rad.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_sensor.h \
		mavlink/include/c_library_v2/common/mavlink_msg_sim_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_radio_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/include/c_library_v2/common/mavlink_msg_timesync.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_trigger.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_gps.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_optical_flow.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_imu2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_entry.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_request_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_erase.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_request_end.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_inject_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps2_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_power_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_serial_control.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_rtk.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps2_rtk.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_imu3.h \
		mavlink/include/c_library_v2/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/include/c_library_v2/common/mavlink_msg_encapsulated_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_distance_sensor.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_request.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_check.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_report.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_pressure2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_att_pos_mocap.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_actuator_control_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_altitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_resource_request.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_pressure3.h \
		mavlink/include/c_library_v2/common/mavlink_msg_follow_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_control_system_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_battery_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_autopilot_version.h \
		mavlink/include/c_library_v2/common/mavlink_msg_landing_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_fence_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_estimator_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_wind_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_input.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_rtcm_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_high_latency.h \
		mavlink/include/c_library_v2/common/mavlink_msg_high_latency2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vibration.h \
		mavlink/include/c_library_v2/common/mavlink_msg_home_position.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_home_position.h \
		mavlink/include/c_library_v2/common/mavlink_msg_message_interval.h \
		mavlink/include/c_library_v2/common/mavlink_msg_extended_sys_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_adsb_vehicle.h \
		mavlink/include/c_library_v2/common/mavlink_msg_collision.h \
		mavlink/include/c_library_v2/common/mavlink_msg_v2_extension.h \
		mavlink/include/c_library_v2/common/mavlink_msg_memory_vect.h \
		mavlink/include/c_library_v2/common/mavlink_msg_debug_vect.h \
		mavlink/include/c_library_v2/common/mavlink_msg_named_value_float.h \
		mavlink/include/c_library_v2/common/mavlink_msg_named_value_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_statustext.h \
		mavlink/include/c_library_v2/common/mavlink_msg_debug.h \
		mavlink/include/c_library_v2/common/mavlink_msg_setup_signing.h \
		mavlink/include/c_library_v2/common/mavlink_msg_button_change.h \
		mavlink/include/c_library_v2/common/mavlink_msg_play_tune.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_settings.h \
		mavlink/include/c_library_v2/common/mavlink_msg_storage_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_capture_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_image_captured.h \
		mavlink/include/c_library_v2/common/mavlink_msg_flight_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mount_orientation.h \
		mavlink/include/c_library_v2/common/mavlink_msg_logging_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_logging_data_acked.h \
		mavlink/include/c_library_v2/common/mavlink_msg_logging_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_video_stream_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_video_stream_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_manager_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_manager_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_manager_set_attitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_device_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_device_set_attitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_device_attitude_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		mavlink/include/c_library_v2/common/mavlink_msg_wifi_config_ap.h \
		mavlink/include/c_library_v2/common/mavlink_msg_protocol_version.h \
		mavlink/include/c_library_v2/common/mavlink_msg_ais_vessel.h \
		mavlink/include/c_library_v2/common/mavlink_msg_uavcan_node_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_uavcan_node_info.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_request_read.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_value.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_set.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_obstacle_distance.h \
		mavlink/include/c_library_v2/common/mavlink_msg_odometry.h \
		mavlink/include/c_library_v2/common/mavlink_msg_trajectory_representation_waypoints.h \
		mavlink/include/c_library_v2/common/mavlink_msg_trajectory_representation_bezier.h \
		mavlink/include/c_library_v2/common/mavlink_msg_cellular_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_isbd_link_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_raw_rpm.h \
		mavlink/include/c_library_v2/common/mavlink_msg_utm_global_position.h \
		mavlink/include/c_library_v2/common/mavlink_msg_debug_float_array.h \
		mavlink/include/c_library_v2/common/mavlink_msg_orbit_execution_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_smart_battery_info.h \
		mavlink/include/c_library_v2/common/mavlink_msg_smart_battery_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_actuator_output_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_time_estimate_to_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_tunnel.h \
		mavlink/include/c_library_v2/common/mavlink_msg_onboard_computer_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_component_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_play_tune_v2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_supported_tunes.h \
		mavlink/include/c_library_v2/common/mavlink_msg_wheel_distance.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_basic_id.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_location.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_authentication.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_self_id.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_system.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_operator_id.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_message_pack.h \
		mavlink/include/c_library_v2/mavlink_get_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

serial.o: serial.cpp serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial.o serial.cpp

camera.o: camera.cpp camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

telemetry.o: telemetry.cpp telemetry.h \
		mavlink/include/c_library_v2/common/mavlink.h \
		mavlink/include/c_library_v2/common/version.h \
		mavlink/include/c_library_v2/common/common.h \
		mavlink/include/c_library_v2/protocol.h \
		mavlink/include/c_library_v2/mavlink_types.h \
		mavlink/include/c_library_v2/mavlink_helpers.h \
		mavlink/include/c_library_v2/checksum.h \
		mavlink/include/c_library_v2/mavlink_conversions.h \
		mavlink/include/c_library_v2/mavlink_sha256.h \
		mavlink/include/c_library_v2/common/mavlink_msg_heartbeat.h \
		mavlink/include/c_library_v2/common/mavlink_msg_sys_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_system_time.h \
		mavlink/include/c_library_v2/common/mavlink_msg_ping.h \
		mavlink/include/c_library_v2/common/mavlink_msg_change_operator_control.h \
		mavlink/include/c_library_v2/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_auth_key.h \
		mavlink/include/c_library_v2/common/mavlink_msg_link_node_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_mode.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_request_read.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_value.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_set.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_raw_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_imu.h \
		mavlink/include/c_library_v2/common/mavlink_msg_raw_imu.h \
		mavlink/include/c_library_v2/common/mavlink_msg_raw_pressure.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_pressure.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude_quaternion.h \
		mavlink/include/c_library_v2/common/mavlink_msg_local_position_ned.h \
		mavlink/include/c_library_v2/common/mavlink_msg_global_position_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_servo_output_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_item.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_set_current.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_current.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_count.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_clear_all.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_item_reached.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_global_origin.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_map_rc.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_request_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_changed.h \
		mavlink/include/c_library_v2/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/include/c_library_v2/common/mavlink_msg_safety_allowed_area.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_nav_controller_output.h \
		mavlink/include/c_library_v2/common/mavlink_msg_global_position_int_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels.h \
		mavlink/include/c_library_v2/common/mavlink_msg_request_data_stream.h \
		mavlink/include/c_library_v2/common/mavlink_msg_data_stream.h \
		mavlink/include/c_library_v2/common/mavlink_msg_manual_control.h \
		mavlink/include/c_library_v2/common/mavlink_msg_rc_channels_override.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mission_item_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vfr_hud.h \
		mavlink/include/c_library_v2/common/mavlink_msg_command_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_command_long.h \
		mavlink/include/c_library_v2/common/mavlink_msg_command_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_manual_setpoint.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_attitude_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_attitude_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/include/c_library_v2/common/mavlink_msg_position_target_local_ned.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_position_target_global_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_controls.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_actuator_controls.h \
		mavlink/include/c_library_v2/common/mavlink_msg_optical_flow.h \
		mavlink/include/c_library_v2/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vision_position_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/include/c_library_v2/common/mavlink_msg_highres_imu.h \
		mavlink/include/c_library_v2/common/mavlink_msg_optical_flow_rad.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_sensor.h \
		mavlink/include/c_library_v2/common/mavlink_msg_sim_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_radio_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/include/c_library_v2/common/mavlink_msg_timesync.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_trigger.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_gps.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_optical_flow.h \
		mavlink/include/c_library_v2/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_imu2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_entry.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_request_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_erase.h \
		mavlink/include/c_library_v2/common/mavlink_msg_log_request_end.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_inject_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps2_raw.h \
		mavlink/include/c_library_v2/common/mavlink_msg_power_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_serial_control.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_rtk.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps2_rtk.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_imu3.h \
		mavlink/include/c_library_v2/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/include/c_library_v2/common/mavlink_msg_encapsulated_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_distance_sensor.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_request.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_check.h \
		mavlink/include/c_library_v2/common/mavlink_msg_terrain_report.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_pressure2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_att_pos_mocap.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_actuator_control_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_altitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_resource_request.h \
		mavlink/include/c_library_v2/common/mavlink_msg_scaled_pressure3.h \
		mavlink/include/c_library_v2/common/mavlink_msg_follow_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_control_system_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_battery_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_autopilot_version.h \
		mavlink/include/c_library_v2/common/mavlink_msg_landing_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_fence_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_estimator_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_wind_cov.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_input.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gps_rtcm_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_high_latency.h \
		mavlink/include/c_library_v2/common/mavlink_msg_high_latency2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_vibration.h \
		mavlink/include/c_library_v2/common/mavlink_msg_home_position.h \
		mavlink/include/c_library_v2/common/mavlink_msg_set_home_position.h \
		mavlink/include/c_library_v2/common/mavlink_msg_message_interval.h \
		mavlink/include/c_library_v2/common/mavlink_msg_extended_sys_state.h \
		mavlink/include/c_library_v2/common/mavlink_msg_adsb_vehicle.h \
		mavlink/include/c_library_v2/common/mavlink_msg_collision.h \
		mavlink/include/c_library_v2/common/mavlink_msg_v2_extension.h \
		mavlink/include/c_library_v2/common/mavlink_msg_memory_vect.h \
		mavlink/include/c_library_v2/common/mavlink_msg_debug_vect.h \
		mavlink/include/c_library_v2/common/mavlink_msg_named_value_float.h \
		mavlink/include/c_library_v2/common/mavlink_msg_named_value_int.h \
		mavlink/include/c_library_v2/common/mavlink_msg_statustext.h \
		mavlink/include/c_library_v2/common/mavlink_msg_debug.h \
		mavlink/include/c_library_v2/common/mavlink_msg_setup_signing.h \
		mavlink/include/c_library_v2/common/mavlink_msg_button_change.h \
		mavlink/include/c_library_v2/common/mavlink_msg_play_tune.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_settings.h \
		mavlink/include/c_library_v2/common/mavlink_msg_storage_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_capture_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_camera_image_captured.h \
		mavlink/include/c_library_v2/common/mavlink_msg_flight_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_mount_orientation.h \
		mavlink/include/c_library_v2/common/mavlink_msg_logging_data.h \
		mavlink/include/c_library_v2/common/mavlink_msg_logging_data_acked.h \
		mavlink/include/c_library_v2/common/mavlink_msg_logging_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_video_stream_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_video_stream_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_manager_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_manager_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_manager_set_attitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_device_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_device_set_attitude.h \
		mavlink/include/c_library_v2/common/mavlink_msg_gimbal_device_attitude_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		mavlink/include/c_library_v2/common/mavlink_msg_wifi_config_ap.h \
		mavlink/include/c_library_v2/common/mavlink_msg_protocol_version.h \
		mavlink/include/c_library_v2/common/mavlink_msg_ais_vessel.h \
		mavlink/include/c_library_v2/common/mavlink_msg_uavcan_node_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_uavcan_node_info.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_request_read.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_request_list.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_value.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_set.h \
		mavlink/include/c_library_v2/common/mavlink_msg_param_ext_ack.h \
		mavlink/include/c_library_v2/common/mavlink_msg_obstacle_distance.h \
		mavlink/include/c_library_v2/common/mavlink_msg_odometry.h \
		mavlink/include/c_library_v2/common/mavlink_msg_trajectory_representation_waypoints.h \
		mavlink/include/c_library_v2/common/mavlink_msg_trajectory_representation_bezier.h \
		mavlink/include/c_library_v2/common/mavlink_msg_cellular_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_isbd_link_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_raw_rpm.h \
		mavlink/include/c_library_v2/common/mavlink_msg_utm_global_position.h \
		mavlink/include/c_library_v2/common/mavlink_msg_debug_float_array.h \
		mavlink/include/c_library_v2/common/mavlink_msg_orbit_execution_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_smart_battery_info.h \
		mavlink/include/c_library_v2/common/mavlink_msg_smart_battery_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_actuator_output_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_time_estimate_to_target.h \
		mavlink/include/c_library_v2/common/mavlink_msg_tunnel.h \
		mavlink/include/c_library_v2/common/mavlink_msg_onboard_computer_status.h \
		mavlink/include/c_library_v2/common/mavlink_msg_component_information.h \
		mavlink/include/c_library_v2/common/mavlink_msg_play_tune_v2.h \
		mavlink/include/c_library_v2/common/mavlink_msg_supported_tunes.h \
		mavlink/include/c_library_v2/common/mavlink_msg_wheel_distance.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_basic_id.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_location.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_authentication.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_self_id.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_system.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_operator_id.h \
		mavlink/include/c_library_v2/common/mavlink_msg_open_drone_id_message_pack.h \
		mavlink/include/c_library_v2/mavlink_get_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o telemetry.o telemetry.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

